# Generated by Django 5.2 on 2025-05-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=255)),
                ("name_ar", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("calories", models.IntegerField()),
            ],
        ),
    ]
