# Generated by Django 5.2 on 2025-05-17 22:58

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_search_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="product",
            name="search_vector",
        ),
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="nutritional_info",
            field=models.JSONField(default=123),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["name_en"], name="products_pr_name_en_adbb83_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["name_ar"], name="products_pr_name_ar_3d9777_btree"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["brand"], name="products_pr_brand_bf5937_btree"
            ),
        ),
    ]
