# Generated by Django 5.2 on 2025-05-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_myfile_remove_product_calories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="nutritional_info",
            field=models.TextField(),
        ),
    ]
