# Generated by Django 5.2 on 2025-05-18 02:23

import datetime
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_search_vector_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_name_en_adbb83_btree",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_name_ar_3d9777_btree",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_brand_bf5937_btree",
        ),
        migrations.RemoveField(
            model_name="product",
            name="nutritional_info",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 18, 2, 22, 58, 76966, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_ar"], name="name_ar_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_en"], name="name_en_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
